/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_android_aec_util_WebRtcUtil */

#ifndef _Included_com_android_aec_util_WebRtcUtil
#define _Included_com_android_aec_util_WebRtcUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_android_aec_util_WebRtcUtil
 * Method:    init
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_android_aec_util_WebRtcUtil_init
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_android_aec_util_WebRtcUtil
 * Method:    free
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_android_aec_util_WebRtcUtil_free
  (JNIEnv *, jclass);

/*
 * Class:     com_android_aec_util_WebRtcUtil
 * Method:    BufferFarend
 * Signature: ([BJ)I
 */
JNIEXPORT jint JNICALL Java_com_android_aec_util_WebRtcUtil_BufferFarend
  (JNIEnv *, jclass, jbyteArray, jlong);

/*
 * Class:     com_android_aec_util_WebRtcUtil
 * Method:    process
 * Signature: ([B[BJJJ)I
 */
JNIEXPORT jint JNICALL Java_com_android_aec_util_WebRtcUtil_process
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jlong, jlong, jlong);

/*
 * Class:     com_android_aec_util_WebRtcUtil
 * Method:    bufferFarendAndProcess
 * Signature: ([B[B[BIIIFF)I
 */
JNIEXPORT jint JNICALL Java_com_android_aec_util_WebRtcUtil_bufferFarendAndProcess
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jbyteArray, jint, jint, jint, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
